[tox]
skip_missing_interpreters = True

envlist =
	py310-dj{52}
	py311-dj{52}
	py312-dj{52,60}
	py313-dj{52,60}
	py314-dj{52,60}
	ruff,docs

[testenv]
commands = python runtests.py {posargs}
package = editable
extras = testing
pip_pre = True
setenv = PYTHONDONTWRITEBYTECODE=1
passenv = "DJANGO_SETTINGS_MODULE,DATABASE_URL"

deps =
	dj52: Django~=5.2.0
	dj60: Django~=6.0.0
	postgres: psycopg2
	mysql: mysqlclient

[testenv:ruff]
basepython = python3
commands = ruff check enumchoicefield/

[testenv:docs]
basepython = python3
extras = testing,docs
changedir = docs
allowlist_externals = make
commands = make SPHINXOPTS=-nW clean html
