# Generated by Django 2.0.1 on 2018-01-30 18:35

from django.db import migrations
import enumchoicefield.fields
import enumchoicefield.tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nullablechoicemodel',
            name='choice',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=enumchoicefield.tests.models.MyEnum, max_length=3, null=True),
        ),
    ]
